### ISSUE TITLE
Undefined references on Linux

### ISSUE THREAD

**Issue by troublescooter** [halfwit/searchfs#1]
I was trying to build this on Linux and I got undefined references, see below. I fixed it by removing -static and adding -lpthread to the flags passed to 9l.

    /usr/lib/plan9/bin/9l -o o.searchfs searchfs.o -static
    /usr/bin/ld: /usr/lib/plan9/lib/lib9.a(_p9dir.o): in function `_p9dir':
    (.text+0x3c3): warning: Using 'getgrgid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
    /usr/bin/ld: (.text+0x40c): warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
    /usr/bin/ld: /usr/lib/plan9/lib/lib9.a(_p9dialparse.o): in function `p9dialparse':
    (.text+0x484): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
    /usr/bin/ld: (.text+0x3a4): warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
    /usr/bin/ld: (.text+0x287): warning: Using 'getservbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
        /usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/libgcc_eh.a(unwind-dw2-fde-dip.o): in function `__register_frame_info_bases.part.5':
    (.text+0x16a9): undefined reference to `pthread_mutex_lock'
    /usr/bin/ld: (.text+0x16dd): undefined reference to `pthread_mutex_unlock'
        /usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/libgcc_eh.a(unwind-dw2-fde-dip.o): in function `__register_frame_info_table_bases':
    (.text+0x17bd): undefined reference to `pthread_mutex_lock'
    /usr/bin/ld: (.text+0x17f1): undefined reference to `pthread_mutex_unlock'
        /usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/libgcc_eh.a(unwind-dw2-fde-dip.o): in function `__deregister_frame_info_bases':
    (.text+0x1883): undefined reference to `pthread_mutex_lock'
    /usr/bin/ld: (.text+0x1906): undefined reference to `pthread_mutex_unlock'
        /usr/bin/ld: (.text+0x193e): undefined reference to `pthread_mutex_unlock'
    /usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/libgcc_eh.a(unwind-dw2-fde-dip.o): in function `_Unwind_Find_FDE':
    (.text+0x1a75): undefined reference to `pthread_mutex_lock'
        /usr/bin/ld: (.text+0x1ba9): undefined reference to `pthread_mutex_unlock'
    /usr/bin/ld: (.text+0x1bea): undefined reference to `pthread_mutex_unlock'
    /usr/bin/ld: /usr/lib/plan9/lib/libthread.a(pthread.o): in function `startprocfn':
        (.text+0x23): undefined reference to `pthread_detach'
    /usr/bin/ld: (.text+0x30): undefined reference to `pthread_exit'
    /usr/bin/ld: /usr/lib/plan9/lib/libthread.a(pthread.o): in function `_threadlock':
        (.text+0x74): undefined reference to `pthread_mutex_lock'
    /usr/bin/ld: (.text+0xa9): undefined reference to `pthread_mutex_trylock'
    /usr/bin/ld: (.text+0xcb): undefined reference to `pthread_mutex_lock'
        /usr/bin/ld: (.text+0xdd): undefined reference to `pthread_mutexattr_init'
    /usr/bin/ld: (.text+0xe7): undefined reference to `pthread_mutexattr_settype'
    /usr/bin/ld: (.text+0xf2): undefined reference to `pthread_mutex_init'
        /usr/bin/ld: (.text+0xfa): undefined reference to `pthread_mutexattr_destroy'
    /usr/bin/ld: (.text+0x10c): undefined reference to `pthread_mutex_unlock'
    /usr/bin/ld: /usr/lib/plan9/lib/libthread.a(pthread.o): in function `_threadunlock':
        (.text+0x129): undefined reference to `pthread_mutex_unlock'
    /usr/bin/ld: /usr/lib/plan9/lib/libthread.a(pthread.o): in function `_procsleep':
    (.text+0x154): undefined reference to `pthread_cond_init'
        /usr/bin/ld: (.text+0x16a): undefined reference to `pthread_cond_wait'
    /usr/bin/ld: (.text+0x172): undefined reference to `pthread_cond_destroy'
    /usr/bin/ld: /usr/lib/plan9/lib/libthread.a(pthread.o): in function `_procwakeupandunlock':
        (.text+0x1df): undefined reference to `pthread_cond_signal'
    /usr/bin/ld: /usr/lib/plan9/lib/libthread.a(pthread.o): in function `_procstart':
    (.text+0x23b): undefined reference to `pthread_create'
        /usr/bin/ld: /usr/lib/plan9/lib/libthread.a(pthread.o): in function `_threadpexit':
    (.text+0x357): undefined reference to `pthread_exit'
    /usr/bin/ld: /usr/lib/plan9/lib/libthread.a(pthread.o): in function `_procwakeup':
        (.text+0x1ad): undefined reference to `pthread_cond_signal'
    /usr/bin/ld: /usr/lib/plan9/lib/libthread.a(pthread.o): in function `_threadproc':
    (.text+0x28c): undefined reference to `pthread_getspecific'
        /usr/bin/ld: /usr/lib/plan9/lib/libthread.a(pthread.o): in function `_threadsetproc':
    (.text+0x29f): undefined reference to `pthread_setspecific'
    /usr/bin/ld: /usr/lib/plan9/lib/libthread.a(pthread.o): in function `_pthreadinit':
        (.text+0x2f3): undefined reference to `pthread_key_create'
    /usr/bin/ld: (.text+0x339): undefined reference to `pthread_key_create'
    collect2: error: ld returned 1 exit status

**Comment by halfwit** [comment]
Awesome, I had only tested this on FreeBSD prior, good catch!

**Comment by troublescooter** [comment]
Thanks.
I thought I also tried adding -lpthread without removing -static. I just retried that in order to doublecheck it doesn't statically link, but apparently that too works now. With exception of a couple of warnings seemingly related to glibc's inability to create completely statically linked binaries, static linking is fine.

**Comment by halfwit** [comment]
I'm gonna open this until I test that Linux stuff is working as expected, when I can build it here. Later today likely

**Comment by halfwit** [comment]
The build flag is there now, I'm going to test on Linux on my end to make sure the other changes that got swept up in this commit didn't cause a regression
